// app/impressum/page.tsx

export const metadata = {
  title: 'Legal Notice | We pay your prompt',
};

export default function ImpressumPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <div className="max-w-3xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-semibold mb-4">Legal Notice / Imprint</h1>

        {/* 1. Site owner / Angaben nach § 5 TMG */}
        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Site Owner / Provider</h2>
          <p>
            <strong>Operator of this website and the &quot;We pay your prompt&quot; service</strong>
            <br />
            Mario von Bassen
            <br />
            Gressengasse 1
            <br />
            97070 Würzburg
            <br />
            Germany
          </p>
          <p>
            Email:{' '}
            <a
              href="mailto:mariovonbassen@gmail.com"
              className="underline underline-offset-2 text-zinc-100 hover:text-zinc-300"
            >
              mariovonbassen@gmail.com
            </a>
          </p>
        </section>

        {/* 2. Responsibility for content / § 55 Abs. 2 RStV */}
        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">
            Responsibility for Content (§ 55 para. 2 RStV)
          </h2>
          <p>
            Responsible for journalistically-editorial content within the meaning of
            § 55 para. 2 RStV:
          </p>
          <p>
            <strong>Mario von Bassen</strong>
            <br />
            Gressengasse 1
            <br />
            97070 Würzburg
            <br />
            Germany
          </p>
          <p>
            The contents of this website have been created with great care.
            Nevertheless, no guarantee can be given for the accuracy, completeness,
            or timeliness of the information provided. As a service provider, we are
            responsible for our own content on these pages in accordance with
            applicable laws.
          </p>
          <p>
            Content generated by AI models is to be understood as suggestions only
            and does not replace individual professional advice (e.g. legal, tax,
            medical, or financial advice). Any liability for actions taken solely on
            the basis of AI-generated responses is excluded.
          </p>
        </section>

        {/* 3. Data protection contact */}
        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Data Protection Contact</h2>
          <p>
            For questions regarding data protection or to exercise your rights
            (e.g. access, deletion, objection), please contact:
          </p>
          <p>
            <strong>Mario von Bassen</strong>
            <br />
            Email:{' '}
            <a
              href="mailto:mariovonbassen@gmail.com"
              className="underline underline-offset-2 text-zinc-100 hover:text-zinc-300"
            >
              mariovonbassen@gmail.com
            </a>
            <br />
            Phone: +49&nbsp;1577&nbsp;/&nbsp;3633756
          </p>
        </section>

        {/* 4. Responsibility for external links / Haftungshinweis */}
        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">
            Responsibility for External Links
          </h2>
          <p>
            Our website may contain links to external third-party websites. We have
            no influence on the content of those websites. Therefore, we cannot
            assume any liability for such external content. The respective provider
            or operator of the linked pages is always responsible for their content.
          </p>
          <p>
            Despite careful content control, we assume no liability for the content
            of external links. The operators of the linked pages are solely
            responsible for their content.
          </p>
        </section>

        {/* 5. Copyright */}
        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Copyright</h2>
          <p>
            The content and works created by the site operator on this website are
            subject to copyright and other intellectual property laws. Contributions
            by third parties are marked as such where applicable. Any reproduction,
            editing, distribution, or any kind of exploitation outside the limits of
            copyright law requires the prior written consent of the respective
            author or creator.
          </p>
        </section>

        {/* Hinweis */}
        <section className="space-y-2 text-xs text-zinc-500 mt-8">
          <p>
            Note: This legal notice/imprint has been adapted for the
            &quot;We pay your prompt&quot; project and does not constitute legal
            advice. Please have the information reviewed and adapted by a qualified
            legal professional to ensure compliance with the laws applicable to you
            (in particular German TMG, RStV and data protection law).
          </p>
        </section>
      </div>
    </main>
  );
}
