// app/impressum/page.tsx

export const metadata = {
  title: 'Legal Notice | We pay your prompt',
};

export default function ImpressumPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <div className="max-w-3xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-semibold mb-4">Legal Notice / Imprint</h1>

        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Site Owner</h2>
          <p>
            <strong>Operator of this website and service</strong>
            <br />
            {/* TODO: Replace with your actual details */}
            Mario Muster
            <br />
            Musterstraße 1
            <br />
            1010 Vienna
            <br />
            Austria
          </p>
          <p>
            Email:{' '}
            <a
              href="mailto:kontakt@example.com"
              className="underline underline-offset-2 text-zinc-100 hover:text-zinc-300"
            >
              kontakt@example.com
            </a>
            <br />
            {/* optional */}
            Phone: +43&nbsp;000&nbsp;000000
          </p>
          <p>
            {/* TODO: If applicable */}
            Commercial register no.: FN&nbsp;123456&nbsp;z
            <br />
            Register court: Commercial Court of Vienna
            <br />
            VAT ID: ATU&nbsp;12345678
          </p>
        </section>

        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Responsibility for content</h2>
          <p>
            The contents of this website have been created with great care.
            Nevertheless, no guarantee can be given for the accuracy,
            completeness, or timeliness of the information provided. As a
            service provider, we are responsible for our own content on these
            pages in accordance with applicable laws.
          </p>
          <p>
            Content generated by AI models is to be understood as suggestions
            only and does not replace individual professional advice (e.g. legal,
            tax, medical, or financial advice). Any liability for actions taken
            solely on the basis of AI-generated responses is excluded.
          </p>
        </section>

        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Responsibility for external links</h2>
          <p>
            Our website may contain links to external third-party websites. We
            have no influence on the content of those websites. Therefore, we
            cannot assume any liability for such external content. The
            respective provider or operator of the linked pages is always
            responsible for their content.
          </p>
        </section>

        <section className="space-y-2 text-sm text-zinc-200 mb-6">
          <h2 className="text-base font-semibold mb-1">Copyright</h2>
          <p>
            The content and works created by the site operator on this website
            are subject to copyright and other intellectual property laws.
            Contributions by third parties are marked as such where applicable.
            Any reproduction, editing, distribution, or any kind of exploitation
            outside the limits of copyright law requires the prior written
            consent of the respective author or creator.
          </p>
        </section>

        <section className="space-y-2 text-xs text-zinc-500 mt-8">
          <p>
            Note: This legal notice/imprint is a generic template adapted to the
            &quot;We pay your prompt&quot; project and does not constitute
            legal advice. Please have the information reviewed and adapted by a
            qualified legal professional to ensure compliance with the laws
            applicable to you.
          </p>
        </section>
      </div>
    </main>
  );
}
